### ISSUE TITLE
Shows that start with a number are not parsed correctly

### ISSUE THREAD

**Issue by stevezau** [wackou/guessit#181]
guessit "90.Day.Fiance.S02E07.I.Have.To.Tell.You.Something.720p.HDTV.x264-W4F"

For: 90.Day.Fiance.S02E07.I.Have.To.Tell.You.Something.720p.HDTV.x264-W4F
GuessIt found: {
    [0.60] "episodeNumber": 7, 
    [1.00] "extension": "x264-w4f", 
    [1.00] "format": "HDTV", 
    [1.00] "season": 2, 
    [0.40] "title": "I Have To Tell You Something", 
    [1.00] "screenSize": "720p", 
    [0.40] "series": "Day Fiance", 
    [1.00] "type": "episode"
}

Series should show 90 day fiance.

It seems this only happens with shows that have 2 digits at the start of their name..

**Comment by Toilal** [comment]
Hi @stevezau, thanks for reporting this issue.

This issue is related to #159 . Fact is that both `90` and `7` can be considered as an episode number. Currently, 90 has a confidence of 40% et 7 has a confidence of 100%. Current behavior is to keep `7` in results with a 60% confidence (100% - 40%). But this is a wrong behavior, as said in #159. 

And even if `90` is removed from final results, it crops the series title but it should not.

So this will be fixed when #159 will be implemented.

**Comment by y** [comment]
Another test case:
Fails: '12 Monkeys - S01E04 [ 12.Monkeys.S01E04.HDTV.x264-KILLERS ]'
Passes: '12.Monkeys.S01E04.HDTV.x264-KILLERS'
