### ISSUE TITLE
Error parsing almost every show

### ISSUE THREAD

**Issue by omaralvarez** [wackou/guessit#185]
I just upgraded subliminal and guessit (10.1.0) and now almost every single show is not parsed correctly, example:

guessit "/media/live/A/Anger.Management.S02E82.720p.HDTV.X264-DIMENSION.mkv" 
For: /media/live/A/**Anger.Management**.S02E82.720p.HDTV.X264-DIMENSION.mkv
GuessIt found: {
    [1.00] "mimetype": "video/x-matroska", 
    [1.00] "episodeNumber": 82, 
    [1.00] "videoCodec": "h264", 
    [1.00] "container": "mkv", 
    [1.00] "format": "HDTV", 
    **----->[0.79] "series": "A",<-------**
    [1.00] "releaseGroup": "DIMENSION", 
    [1.00] "screenSize": "720p", 
    [1.00] "season": 2, 
    [1.00] "type": "episode"
}

**Comment by omaralvarez** [comment]
Update:

The problem has to do with full paths, if I run guessit without the full path it works ok:

guessit "Anger.Management.S02E82.720p.HDTV.X264-DIMENSION.mkv" 
For: Anger.Management.S02E82.720p.HDTV.X264-DIMENSION.mkv
GuessIt found: {
    [1.00] "mimetype": "video/x-matroska", 
    [1.00] "episodeNumber": 82, 
    [1.00] "videoCodec": "h264", 
    [1.00] "container": "mkv", 
    [1.00] "format": "HDTV", 
    [0.70] "series": "Anger Management", 
    [1.00] "releaseGroup": "DIMENSION", 
    [1.00] "screenSize": "720p", 
    [1.00] "season": 2, 
    [1.00] "type": "episode"
}

**Comment by Toilal** [comment]
Thanks for reporting, i'll have a look soon.

**Comment by omaralvarez** [comment]
Thanks for the quick response, please let me know if I can help in any way!

**Comment by Toilal** [comment]
In debug, I can see that there's two guesses for series name : `A` with 0.30 confidence, and `Anger Management` with 0.70 confidence. 

Then, to solve the conflict, [choose_string](https://github.com/wackou/guessit/blob/master/guessit/guess.py#L293-L353) method is called to choose the better guess and update confidence. This function is well documented:

```
    """Function used by merge_similar_guesses to choose between 2 possible
    properties when they are strings.

    If the 2 strings are similar, or one is contained in the other, the latter is returned
    with an increased confidence.

    If the 2 strings are dissimilar, the one with the higher confidence is returned, with
    a weaker confidence.

    Note that here, 'similar' means that 2 strings are either equal, or that they
    differ very little, such as one string being the other one with the 'the' word
    prepended to it.
```

We are in the case `One string is contained in the other` because `A` is contained in `Anger Management`, but problem is that A is returned instead of Anger Management. 

I think this behavior should be change to `One string has a least one common word in the other`, because it doesn't make sense for a single letter ... I'll fix.
