### ISSUE TITLE
12 Angry men classified as episode

### ISSUE THREAD

**Issue by kamaradclimber** [wackou/guessit#188]
`guessit "12 Angry Men (12 hommes en colère) DVDRip VOSTFR.avi"`

returns:
```
For: 12 Angry Men (12 hommes en colère) DVDRip VOSTFR.avi
GuessIt found: {
    [0.80] "language": [
        "en"
    ],
    [1.00] "container": "avi",
    [0.80] "subtitleLanguage": [
        "fr"
    ],
    [0.40] "episodeNumber": 12,
    [1.00] "mimetype": "video/x-msvideo",
    [1.00] "format": "DVD",
    [1.00] "type": "episode",
    [0.40] "series": "Angry Men"
}
```

title is not reported, it is incorrecly classified as episode.

**Comment by djl** [comment]
I just ran into a similar issue. It seems that anything beginning with two digits is classified as an episode while anything beginning with one, three or more digits is classified as a movie:

    $ guessit "1.Angry.Man.1957.mkv" | grep '"type'
        [1.00] "type": "movie"
    $ guessit "12.Angry.Men.1957.mkv" | grep '"type'
        [1.00] "type": "episode"
    $ guessit "123.Angry.Men.1957.mkv" | grep '"type'
        [1.00] "type": "movie"

**Comment by Toilal** [comment]
dji has the explanation. Anything starting with 2 digits will be considered as an episode. 

This is on purpose and really controlled, I can't consider this as a bug.

**Comment by Toilal** [comment]
If you know that you need to scan a movie, you can force the filetype using the `-t` flag.

```
  -t TYPE, --type TYPE  The suggested file type: movie, episode. If undefined,
                        type will be guessed.
```

But maybe I could remove the `nn*` pattern for episode filetype detection ? ... What do you think @wackou ? Maybe based on the low confidence thos pattern returns (`0.4` only, see [guess_episodes_rexps.py#L162-L166](https://github.com/wackou/guessit/blob/master/guessit/transfo/guess_episodes_rexps.py#L162-L166))

**Comment by kamaradclimber** [comment]
There are indeed a few movies starting with a number (not that many with two digits though): http://en.wikipedia.org/wiki/List_of_films:_numbers

**Comment by wackou** [comment]
as far as I am concerned, we can remove the "nn" pattern for detecting episodes (unless it breaks too many tests, in which case it would need to be left as is). The list from wikipedia is very interesting, in the worst case, we could hardcode it so that the pattern "nn" detects an episode unless it is in the list of movies starting with a 2-digit number.

**Comment by VeNoMouS** [comment]
Also get the issue with "12 Monkeys" and using ```guess_episode_info```

**Comment by wackou** [comment]
Another one from https://github.com/wackou/guessit/issues/209: ```36 Vayadhinile (2015) [HD Rip. 500MB. x264. AAC. ESubs][SR Puli][Team SR].mkv```

**Comment by VeNoMouS** [comment]
@Toilal any update when this will actually be resolved ?

Cheers man

**Comment by Toilal** [comment]
Hope soon, I will have some spare time in two weeks.

Some of the mentionned failing guesses could be fixed when working on #159.

For example `12.Monkeys.S01E13.HDTV.x264-ASAP.avi` : `episode` is found with `S01E13` and `12`,  causing a conflict. But `12` should be ignored and reused in the title because it has a lower confidence than `S01E13`. Currently, confidence on conflict properties drops the property in most cases, and that's the issue #159.

Also, if the guess contains `year`, it should be considered as a movie (should solve `36 Vayadhinile (2015)` and `12.Angry.Men.1957.mkv`).

I still have no idea to solve the initial case `12 Angry Men (12 hommes en colère) DVDRip VOSTFR.avi` when no suggested file type is given. For this particular case, it will probably end with a `won't fix`.

**Comment by VeNoMouS** [comment]
Thanks for the update :)

**Comment by Toilal** [comment]
I close this issue, as i don't know how to solve it ... I don't think it's possible without having a hardcoded list of movies starting with numbers.

But other use cases mentionned in the thread are solved though : if it contains a year and an episode number without season, it will go to second pass with type forced to movie. Also, if the episode was found in another pattern, it won't be removed from the series name.

```bash
For: 12.Monkeys.S01E13.HDTV.x264-ASAP.avi
GuessIt found: {
    [1.00] "container": "avi",
    [1.00] "episodeNumber": 13,
    [1.00] "format": "HDTV",
    [0.70] "series": "12 Monkeys",
    [1.00] "season": 1,
    [1.00] "videoCodec": "h264",
    [1.00] "mimetype": "video/x-msvideo",
    [1.00] "releaseGroup": "ASAP",
    [1.00] "type": "episode"
}
For: 36 Vayadhinile (2015).avi
GuessIt found: {
    [1.00] "container": "avi",
    [1.00] "mimetype": "video/x-msvideo",
    [1.00] "year": 2015,
    [0.60] "title": "36 Vayadhinile",
    [1.00] "type": "movie"
}
For: 12.Angry.Men.1957.mkv
GuessIt found: {
    [1.00] "container": "mkv",
    [1.00] "mimetype": "video/x-matroska",
    [1.00] "year": 1957,
    [0.60] "title": "12 Angry Men",
    [1.00] "type": "movie"
}

```
