### ISSUE TITLE
Missing episode list for sample files

### ISSUE THREAD

**Issue by OmgImAlexis** [wackou/guessit#221]
I just tried guessit against a few fake files with generic filename patterns. Is there a reason it fails on these?

````
➜  test  guessit Show.Name.S01E02.S01E03.Source.Quality.Etc-Group.mkv 
For: Show.Name.S01E02.S01E03.Source.Quality.Etc-Group.mkv
GuessIt found: {
    [1.00] "mimetype": "video/x-matroska", 
    [1.00] "container": "mkv", 
    [0.50] "title": "Source Quality Etc-Group", 
    [0.70] "series": "Show Name", 
    [1.00] "type": "episode", 
    [1.00] "season": 1
}
````
````
➜  test  guessit Show\ Name\ -\ S01E02\ -\ S01E03\ -\ S01E04\ -\ Ep\ Name.mkv 
For: Show Name - S01E02 - S01E03 - S01E04 - Ep Name.mkv
GuessIt found: {
    [1.00] "mimetype": "video/x-matroska", 
    [1.00] "episodeNumber": 4, 
    [1.00] "container": "mkv", 
    [0.50] "title": "Ep Name", 
    [0.70] "series": "Show Name", 
    [1.00] "type": "episode", 
    [1.00] "season": 1
}
````

**Comment by Toilal** [comment]
This is related to #159. To make it short, when multiple values for `episodeNumber` are found, it currently removes all of them because they all have the same confidence and guessit don't know which one to choose ...

But your example is good, and it's probably a good idea to convert them to `episodeList` when multiple `episodeNumber` are found.

But it could cause other problems : What to do if something like this : `Show Name - S01E02 - S02E03 - S03E04 - Ep Name.mkv` ? Should it give `seasonList: [1, 2, 3]` and `episodeList: [2, 3, 4]` ?

**Comment by OmgImAlexis** [comment]
There should never be a file like that, the only reason you get multiples is if a show aires multiple episodes as a single episode so they're always going to have the same season. There'd be no way you'd ever get for example season 1 and season 2 in the same file, if you did that file would be considered fake.

**Comment by OmgImAlexis** [comment]
If you're looking for more samples to try that actually get used look at the regex examples in SickRage, almost all of the sample filenames in there actually show up on sites and with SickRage switching from Regex to guessit I'd assume they'll be finding bugs with files similar to their sample filenames so it'd be nice to have those fixed before they fully switch over.

https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/name_parser/regexes.py

**Comment by Toilal** [comment]
Great, i'll try to add all those files samples to unit tests.

**Comment by Toilal** [comment]
This particular one is fixed, but there are other issues on sickrage examples, please review #222 issue.

Those issues are often related to `episodeList` support.
