### ISSUE TITLE
Detects episode as movie with difficult path name

### ISSUE THREAD

**Issue by pannal** [wackou/guessit#233]
```
guess_file_info('/Volumes/Blablabla/Movies/TV Shows/Unwatched/Long Series Name/Season 09/Long Series Name - S09E04/Seriesname.S09E04.720p.HDTV.X264-GRP.mkv')
```
results in

```
{u'container': u'mkv',
 u'format': u'HDTV',
 u'mimetype': 'video/x-matroska',
 u'releaseGroup': u'GRP',
 u'screenSize': u'720p',
 u'title': u'Seriesname S09E04',
 u'type': u'movie',
 u'unidentified': [u'TV Shows',
                   u'Volumes',
                   u'Unwatched',
                   u'Movies',
                   u'Season 09',
                   u'Long Series Name',
                   u'Blablabla',
                   u'S09E04'],
 u'videoCodec': u'h264'}
```

If the "Movies" part is removed in the path, it yields expected results. This is a problem for Mac users, though, as their default media library seems to have that name (I'm passing on this issue on behalf of someone else).

**Comment by ledge74** [comment]
Good thing you could track down the issue.

However, as Plex libraries already have types specified (movies or shows), couldn't you indicate the type to guessit beforehand? (reading the docs it seems possible). This would avoid any kind of path naming problem in the future.

**Comment by Toilal** [comment]
Actually, this is done on purpose, when "Movies" directory is inside the path, it automatically force the filetype to movie. I think it's not a good idea, as you say having this directory in the path doesn't always mean it's a movie ...

**Comment by Toilal** [comment]
It will be fixed in guessit 2.x, but it's currently an unreleased and work in progress version (see 2.x branch). I hope there will be an alpha soon, and i'll write an easy to follow migration plan for applications that embeds guessit.

Using current 2.x branch, it yields expected results I think.

```
For: /Volumes/Blablabla/Movies/TV Shows/Unwatched/Long Series Name/Season 09/Long Series Name - S09E04/Seriesname.S09E04.720p.HDTV.X264-GRP.mkv
GuessIt found: {
    "title": "Long Series Name",
    "episodeTitle": "Seriesname",
    "season": 9,
    "episodeNumber": 4,
    "screenSize": "720p",
    "format": "HDTV",
    "videoCodec": "h264",
    "releaseGroup": "GRP",
    "extension": "mkv"
}
```

As you can see, there's no confidence anymore and some properties where renamed (`series => title` and `title => episodeTitle`). The `type` property is still to implement, it was a central concept in guessit 0.x/1.x but will be really secondray in 2.x.
